### ISSUE TITLE
Crash (when running in real MC or Through gradle task)

### ISSUE THREAD

**Issue by downloadpizza** [CottonMC/Trion#1]
**Describe the bug**
Crashing when trying to open new world

**To Reproduce**
1. Compile
2. Run the gradle minecraft client task
3. Create new world

**Expected behavior**
The world should open 

**Logs**
[crash-2020-05-13_14.34.57-server.txt](https://github.com/CottonMC/Trion/files/4621981/crash-2020-05-13_14.34.57-server.txt)

**Version of the (please complete the following information):**
 - Trion 1.0.0
 - Fabric API 0.4.32+build.292-1.15
 - Minecraft 1.15.2

**Additional context**
Linux (Pop_OS!) 20.04
openjdk 1.8.0 - 252

**Comment by downloadpizza** [comment]
Apparently the error is in the [TrionComponentImpl:250](https://github.com/CottonMC/Trion/blob/e9810b29f40666f39eb82265887736294de0c5d0/src/main/java/io/github/cottonmc/trion/impl/TrionComponentImpl.java#L250)
`tag.put("Config", config.toTag(new CompoundTag()));`
Ill investigate further

**Comment by downloadpizza** [comment]
For some reason the `config` variable [TrionComponentImpl:33](https://github.com/CottonMC/Trion/blob/e9810b29f40666f39eb82265887736294de0c5d0/src/main/java/io/github/cottonmc/trion/impl/TrionComponentImpl.java#L33) is null

**Comment by Gabgab2003** [comment]
commenting everything out and replacing it with an empty compund tag seems to work, very weird

**Comment by downloadpizza** [comment]
Thanks
